export const wordsEnglish = [
    "dog",
    "going",
    "hungry",
    "gold",
    "park",
    "hidden",
    "hook",
    "install",
    "hang",
    "book",
    "library",
    "computers",
    "justice",
    "union",
    "unique",
    "universe",
    "hole",
    "coffee",
    "absented",
    "absentee",
    "absenteeism",
    "absentees",
    "absenting",
    "absently",
    "absentminded",
    "absentmindedly",
    "absentmindedness",
    "absents",
    "absinthe",
    "absinthism",
    "absolute",
    "absolutely",
    "absoluteness",
    "absolutes",
    "simple",
    "simpleminded",
    "simpleness",
    "simpler",
    "tree",
    "maths",
    "theories",
    "theorist",
    "theorists",
    "theory",
    "thiamine",
    "thiazine",
    "thiazines",
    "thiazole",
    "thick",
    "thicken",
    "underusing",
    "undervaluation",
    "undervalue",
    "undervalued",
    "undiagnosable",
    "undiagnosed",
    "undid",
    "undies"
]

export const wordsSpanish = [
    "puedes", "ahi", "ti",
    "vida", "ver", "alguien",
    "sr", "hasta", "sin", "mi",
    "solo", "años", "sobre", "decir", "uno", "siempre", "oh",
    "ir", "cosas", "tambien", "antes", "has", "ni", "mis", "dia",
    "estar", "estamos", "noche", "nadie", "otra", "quiere", "parece",
    "nosotros", "poco", "padre", "trabajo", "gente", "mira", "vas",
    "sea", "les", "donde", "mismo", "hecho", "ellos", "dijo", "pasa",
    "dinero", "hijo", "tal", "otro", "hablar", "seguro", "claro",
    "estas", "lugar", "mundo", "amigo", "espera", "mierda", "han",
    "tus", "sabe", "despues", "momento", "desde", "fuera", "cosa",
    "tipo", "mañana", "podemos", "dije", "gran", "necesito", "estado",
    "podria", "acuerdo", "papa", "tener", "dice", "mio", "crees", "buena",
    "gusta", "nuestro", "nuevo", "sera", "haciendo", "dias", "nombre", "buen",
    "habia", "ven", "tres", "menos", "debe", "tenia",
    "mal", "conmigo", "madre", "hoy", "quien", "sido",
    "mama", "tienen", "luego", "todas", "alli", "toda",
    "hora", "mujer", "visto", "haces", "importa", "contigo",
    "terroristas", "empece", "pongan", "phoebe", "moto", "opinas",
    "habilidad", "entren", "descubierto", "convertido", "asegúrate",
    "summer", "quede", "kilos", "florida", "tomara", "sufrir", "mental",
    "lograr", "instituto", "um", "serlo", "rapido", "plato", "llorando",
    "vayase", "sucediendo", "robaron", "alemania", "bolas", "luthor", "pasaria",
    "ocurra", "ilegal", "fresco", "falso", "abogados", "tomalo", "mando", "cuan",
    "cuales", "botas", "tiburones", "marissa", "grado", "deseas", "archivos", "adivina",
    "cruz", "campaña", "asustada", "centavos", "vivimos", "galletas", "frecuencia", "daños", "minas"
]

export const wordsSpecial = [
    "na solo eso",
    "no mames",
    "explicao",
    "por la caraaa",
    "mfatm",
    "see? naa",
    "na que cabron",
    "hombre si te pones asi",
    "hostias que pedazo de cacho de puto cabron no?",
    "amalio negro",
    "si mira te cuento",
    "pues a ver primero",
    "padel con los hermanitos",
    "sabeis a quien me monto yo?",
]

export const textEnglish = {
    letters: "Letters tried",
    words: "Words tried",
    placeholder: "Input a letter or a word...",
    submitbutton: "Submit",
    restartbutton: "Restart Game",
    fails: "Fails: ",
    validmsg: "Please enter a valid word",
    winmsg: "You won the game!",
    losemsg: "You lost, the word was ",
    repeatmsg: "Please don't repeat words or letters"
}

export const textSpanish = {
    letters: "Letras usadas",
    words: "Palabras usadas",
    placeholder: "Introduce una letra o una palabra...",
    submitbutton: "Enviar",
    restartbutton: "Reiniciar",
    fails: "Fallos: ",
    validmsg: "Introduce una palabra valida",
    winmsg: "Has ganado!",
    losemsg: "Has perdido, la palabra era ",
    repeatmsg: "Porfavor no repitas palabras o letras"
}




// https://github.com/bpropelled/English-Words-Array/blob/master/words.js